/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ApiSendQuoteEmailRouteImport } from './routes/api.send-quote-email'
import { Route as ApiCreatePaymentRouteImport } from './routes/api.create-payment'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendQuoteEmailRoute = ApiSendQuoteEmailRouteImport.update({
  id: '/api/send-quote-email',
  path: '/api/send-quote-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePaymentRoute = ApiCreatePaymentRouteImport.update({
  id: '/api/create-payment',
  path: '/api/create-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/api/create-payment': typeof ApiCreatePaymentRoute
  '/api/send-quote-email': typeof ApiSendQuoteEmailRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/api/create-payment': typeof ApiCreatePaymentRoute
  '/api/send-quote-email': typeof ApiSendQuoteEmailRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/api/create-payment': typeof ApiCreatePaymentRoute
  '/api/send-quote-email': typeof ApiSendQuoteEmailRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/admin/orders'
    | '/admin/quotes'
    | '/api/create-payment'
    | '/api/send-quote-email'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin/orders'
    | '/admin/quotes'
    | '/api/create-payment'
    | '/api/send-quote-email'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/admin/orders'
    | '/admin/quotes'
    | '/api/create-payment'
    | '/api/send-quote-email'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCreatePaymentRoute: typeof ApiCreatePaymentRoute
  ApiSendQuoteEmailRoute: typeof ApiSendQuoteEmailRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-quote-email': {
      id: '/api/send-quote-email'
      path: '/api/send-quote-email'
      fullPath: '/api/send-quote-email'
      preLoaderRoute: typeof ApiSendQuoteEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-payment': {
      id: '/api/create-payment'
      path: '/api/create-payment'
      fullPath: '/api/create-payment'
      preLoaderRoute: typeof ApiCreatePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCreatePaymentRoute: ApiCreatePaymentRoute,
  ApiSendQuoteEmailRoute: ApiSendQuoteEmailRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
